"""empty message

Revision ID: 603b475501da
Revises: 00bd4c657282
Create Date: 2024-11-27 14:52:40.863059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603b475501da'
down_revision = '00bd4c657282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
